query contacts {
  contacts {
    id
    firstName
    lastName
    email
  }
}

query contact {
  contact(id: 1) {
    id
    firstName
    lastName
    email
  }
}

mutation create_jon {
    createContact(firstName: "Jon", lastName: "Snow", email: "jonsnow@thenightswatch.com") {
        id,
        firstName,
        lastName,
        email
    }
}

mutation create_nuevo {
    createContact(firstName: "Juanita", lastName: "Rodriguez Leon", email: "juanita@lalaboral.com") {
        id,
        firstName,
        lastName,
        email
    }
}

mutation create_aegon {
    createContact(firstName: "Aegon", lastName: "Targaryen", email: "aegontargaryen@ironthrone.com") {
        id,
        firstName,
        lastName,
        email
    }
}

mutation update_aegon {
  updateContact(
    id: 2,
    firstName: "Aegon", 
    lastName: "Otoño Duro", 
    email: "aegontargaryen@tronodehierro.es") {
    id
    email
    firstName
    lastName
  
  }
}

mutation update_aegon_partial {
  updateContact(
    id: 2,
    lastName: "Primaveras") { 
    id
    email
    firstName
    lastName
  
  }
}

mutation delete {
    deleteContact(id: 11)
}